In [1]:
def Pipeline(path):
    import warnings
    warnings.filterwarnings("ignore")
    import pandas as pd    
    df=pd.read_csv(path)
    my_titles=['Back-End Developer','Full Stack Developer','Mobile Developer','UI/UX Designer','IT Specialist','Software Engineer','Database Administrator','Data Analyst','Front-End Developer','Tester','Network Engineer','Cyber Security','Machine Learning Engineer','Embedded Systems Engineer','Game Developer','Data Engineer','Dev-Ops']
    
    #df.drop(['company','skills','from'],axis=1,inplace=True)
    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)
    df.job_title=df.job_title.str.replace("\-"," ")
    df.job_title=df.job_title.str.replace("\("," ")
    df.job_title=df.job_title.str.replace("\)"," ")
    df.job_title=df.job_title.str.replace("\/"," ")
    df.job_title=df.job_title.str.replace("\\"," ")
    df.job_title=df.job_title.str.replace("\|"," ")
    df.job_title=df.job_title.str.replace("\_"," ")
    df.job_title=df.job_title.str.lower()
    
    software_words = ['developer','devops','dev-ops','architect','html','css','app','sharepoint','crm','spring','angular',' vue ',' nest ',' node ','nodejs','node\.js','flask','golang','laravel','ruby on rails','cross platform','kotlin','xmarin','swift','react ','flutter','hybrid mobile','django','mongo','apache','nginx','cloud','docker','jira','implement','qa ','javascript','warehouse','intelligen','ai ','bi ','business intelligence','machine learning','computer vision','nlp','deep learning','compu','data engineer','programmer','programming','python','embedded','network','tech','wordpress','backend','frontend','front end','back end','web','linux','windows','mac ','macos','cyber','software','quality','php','it ','\.net','java','c\#','code','android','ios','aws','mobile','system','quality',' end','full stack','tester','fullstack','ui','ux','stack','database','data base','development','data analyst','analyst','data analysis','analytics','data','data science','data scientist','api ','kpi ','erp ','c\+\+','oracle','sql','db','dba']
    software = df[df.job_title.str.contains('|'.join(software_words))]
    
    noise_list=['linux','mac ','obuntu','macos','mac os','windows','unix','pharma','solar','civil engineer','electrical engineer','electricity engineer','search','writ','technician','techinican','marketer','data entry','hr ','content']

    noise0= software[software.job_title.str.contains('|'.join(noise_list))].index
    software.drop(noise0, inplace=True)

    noise1= software[(software.job_title.str.contains('system') & software.job_title.str.contains('admin'))].index
    software.drop(noise1, inplace=True)

    noise2= software[(((software.job_title.str.contains('system')) | (software.job_title.str.contains('software'))) & (software.job_title.str.contains('analyst')) & (~software.job_title.str.contains('business')) & (~software.job_title.str.contains('data')))].index
    software.drop(noise2, inplace=True)

    noise3= software[(software.job_title.str.contains('tech') & software.job_title.str.contains('analyst'))].index
    software.drop(noise3, inplace=True)
    
    def job_replacer(x):
        
        if 'database' in x or 'data base' in x or 'warehouse' in x or 'oracle' in x or 'db ' in x or 'dba ' in x or 'sql' in x:
            return 'Database Administrator'
        elif '.net' in x or 'desktop' in x or 'j2ee' in x or 'jee' in x or 'rust' in x or 'crm' in x or 'java' in x or 'dot net' in x or 'php' in x or 'c#' in x or 'backend' in x or 'back end' in x or 'spring' in x or ' nest ' in x or ' node ' in x or 'nodejs' in x or 'node.js' in x or 'flask' in x or 'golang' in x or 'laravel' in x or 'ruby on rails' in x or 'django' in x or 'mongo' in x or 'apache' in x or 'nginx' in x or 'jira' in x:
            return 'Back-End Developer'
        elif 'front' in x or 'angular' in x or ' vue ' in x or 'react' in x or 'html' in x or 'css' in x:
            return 'Front-End Developer'
        elif 'fullstack' in x or'full stack' in x or ('web' in x and ('develop' in x or 'app' in x or 'support' in x or 'engineer' or 'implement' in x or 'consult' in x or 'program' in x or 'code' in x or 'specialist' in x or 'process' in x or 'operat' in x or 'manag' in x or 'advisor' in x or 'assist' in x)) or 'wordpress' in x or 'javascript' in x or 'solution' in x or 'sharepoint' in x:
            return 'Full Stack Developer'
        elif 'data science' in x or 'data scientist' in x:
            return 'Data Scientist'
        elif 'cloud' in x or 'docker' in x or 'aws' in x or 'api ' in x or 'ops ' in x or 'devops' in x or 'dev-ops' in x:
            return 'Dev-Ops'
        elif 'cyber' in x or 'security' in x:
            return 'Cyber Security'
        elif ('data' in x and 'engineer' in x) or ('big' in x and 'data' in x and 'anal' not in x):
            return 'Data Engineer'
        elif 'embedded' in x:
            return 'Embedded Systems Engineer'
        elif 'network' in x:
            return 'Network Engineer'
        elif 'design' in x or 'ui' in x or 'ux' in x or 'interface' in x:
            return 'UI/UX Designer'
        elif 'test' in x or 'quality' in x or 'qa ' in x or 'qc ' in x:
            return 'Tester'
        elif 'data analyst' in x or 'analyst' in x or ('business' in x and ('analyst' in x or 'intelligen' in x)) or 'data analysis' in x or 'analytics' in x or 'bi ' in x or ('data' in x and ('develop' in x or 'support' in x or 'implement' in x or 'program' in x or 'code' in x or 'specialist' in x or 'process' in x or 'operat' in x or 'manag' in x or 'advisor' in x or 'assist' in x or 'consult' in x or 'big' in x)):
            return 'Data Analyst'
        elif 'machine learning' in x or 'ai ' in x or 'intelligen' in x or 'deep learning' in x or 'computer vision' in x or 'nlp' in x:
            return 'Machine Learning Engineer'
        elif 'it ' in x:
            for title in x :
                if title.find('it ')-1 < 0:
                    return ('IT Specialist')
                elif title[(title.find('it ')-1)] == ' ':
                    return('IT Specialist')
                else :
                    software.drop(software[(software.job_title.str.contains(title))].index , inplace=True)
        elif 'game' in x:
            return 'Game Developer'
        elif 'tech' in x:
            return 'IT Specialist'

        elif ('app' in x and 'web' not in x and ('develop' in x or 'support' in x or 'engineer' or 'consult' in x or 'implement' in x or 'program' in x or 'code' in x or 'specialist' in x or 'process' in x or 'operat' in x or 'manag' in x or 'advisor' in x or 'assist' in x)) or 'android' in x or 'gsm' in x or 'ios' in x or 'mobile' in x or 'cross platform' in x or 'kotlin' in x or 'xmarin' in x or 'swift' in x or 'react native' in x or 'flutter' in x or 'hybrid mobile' in x or 'phone' in x:
            return 'Mobile Developer'
        elif 'software' in x or 'computer' in x or 'architect' in x or 'erp ' in x or 'system' in x or 'develop' in x or 'implement' in x or 'program' in x or 'code' in x:
            return 'Software Engineer'

        else:
            return x

    software.job_title=software.job_title.apply(job_replacer)

    for title in software.job_title:
        if title not in my_titles:
            software.drop(software[(software.job_title==title)].index , inplace=True)


    
    return software

In [2]:
df=Pipeline(r"C:\Users\DELL\Downloads\archive\offersleaks(edited).csv")
df

,city,job_title,company,salary,YearsOfExperience,btackets
1,Cairo,Back-End Developer,Egyptian Takaful Property and Liability,17648.0,3.0,15-20
2,Cairo,Back-End Developer,Hidden Name,17543.0,5.0,15-20
3,Cairo,IT Specialist,Nahdet Misr Publishing Group,5334.0,2.0,5-10
5,Cairo,IT Specialist,Paymob Solutions,3707.0,1.0,2.5-5
11,Cairo,Tester,Concentrix,4416.0,1.0,2.5-5
...,...,...,...,...,...,...
10496,UAE,Software Engineer,Gammal Tech,29940.0,4.0,20-35
10497,UAE,Mobile Developer,Gammal Tech,28090.0,4.0,20-35
10498,UAE,Mobile Developer,Gammal Tech,23022.0,3.0,20-35
10500,USA,Software Engineer,Gammal Tech,27539.0,3.0,20-35
10501,USA,Software Engineer,Gammal Tech,21881.0,5.0,20-35

In [10]:
#df.to_excel(r"C:\Users\DELL\Downloads\archive\mydata.xlsx")